### ISSUE TITLE
Problem with awesome-typescript loader

### ISSUE THREAD

**Issue by Tonio31** [TwanoO67/ngx-admin-lte#1]
Hello,

I'm trying to integrate this, I'm pretty new with Angular2 and Typescript so it's probably my lack of knowledge that prevents me from understanding correctly.

I'm using [Angular Starter ](https://github.com/AngularClass/angular-starter)as a base project. When I install ngx-admin-lte and just add it to my project:

```

import { NgxAdminLteModule } from 'ngx-admin-lte';

  @NgModule({
    ...
  imports: [
    ...
    NgxAdminLteModule,

  ```
 

I got the following errors:
[at-loader] Checking finished with 6 errors
[at-loader] ./node_modules/ngx-admin-lte/src/services/rest.service.ts:55:9
    TS2322: Type 'Observable<any>' is not assignable to type 'Observable<any[]>'.
  Property 'source' is protected but type 'Observable<T>' is not a class derived from 'Observable<T>'.

[at-loader] ./node_modules/ngx-admin-lte/src/services/rest.service.ts:80:9
    TS90010: Type 'Observable<any>' is not assignable to type 'Observable<any>'. Two different types with this name exist, but they are unrelated.
  Property 'source' is protected but type 'Observable<T>' is not a class derived from 'Observable<T>'.

[at-loader] ./node_modules/ngx-admin-lte/src/services/rest.service.ts:92:9
    TS2322: Type 'Observable<any>' is not assignable to type 'Observable<number>'.
  Property 'source' is protected but type 'Observable<T>' is not a class derived from 'Observable<T>'.

[at-loader] ./node_modules/ngx-admin-lte/src/services/rest.service.ts:100:7
    TS2322: Type 'Observable<any>' is not assignable to type 'Observable<number[]>'.
  Property 'source' is protected but type 'Observable<T>' is not a class derived from 'Observable<T>'.

[at-loader] ./node_modules/ngx-admin-lte/src/services/rest.service.ts:106:9
    TS2322: Type 'Observable<any>' is not assignable to type 'Observable<number>'.

[at-loader] ./node_modules/ngx-admin-lte/src/services/rest.service.ts:112:9
    TS2322: Type 'Observable<any>' is not assignable to type 'Observable<Response>'.
  Property 'source' is protected but type 'Observable<T>' is not a class derived from 'Observable<T>'.

Any ideas what I'm doing wrong ?

**Comment by TwanoO67** [comment]
Hello,

Its seems that you have multiple rxjs in your installation

**Comment by Tonio31** [comment]
This are my dependencies in package.json, rxjs is mentionned only once:

"dependencies": {
    "@angular/animations": "~4.1.2",
    "@angular/common": "~4.1.2",
    "@angular/compiler": "~4.1.2",
    "@angular/core": "~4.1.2",
    "@angular/forms": "~4.1.2",
    "@angular/http": "~4.1.2",
    "@angular/platform-browser": "~4.1.2",
    "@angular/platform-browser-dynamic": "~4.1.2",
    "@angular/platform-server": "~4.1.2",
    "@angular/router": "~4.1.2",
    "@angularclass/hmr": "~1.2.2",
    "@angularclass/hmr-loader": "~3.0.2",
    "core-js": "^2.4.1",
    "http-server": "^0.9.0",
    "ie-shim": "^0.1.0",
    "ngx-admin-lte": "^0.2.0",
    "reflect-metadata": "^0.1.10",
    "rxjs": "^5.4.2",
    "zone.js": "0.8.5"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~4.1.2",
    "@types/hammerjs": "^2.0.34",
    "@types/jasmine": "2.5.45",
    "@types/node": "^7.0.37",
    "@types/source-map": "^0.5.0",
    "@types/uglify-js": "^2.6.28",
    "@types/webpack": "^2.2.15",
    "add-asset-html-webpack-plugin": "^1.0.2",
    "angular2-template-loader": "^0.6.2",
    "assets-webpack-plugin": "^3.5.1",
    "awesome-typescript-loader": "~3.1.2",
    "codelyzer": "~2.1.1",
    "copy-webpack-plugin": "^4.0.1",
    "cross-env": "^5.0.0",
    "css-loader": "^0.28.0",
    "exports-loader": "^0.6.4",
    "expose-loader": "^0.7.3",
    "extract-text-webpack-plugin": "~2.1.0",
    "file-loader": "^0.11.1",
    "find-root": "^1.0.0",
    "gh-pages": "^1.0.0",
    "html-webpack-plugin": "^2.28.0",
    "imports-loader": "^0.7.1",
    "inline-manifest-webpack-plugin": "^3.0.1",
    "istanbul-instrumenter-loader": "2.0.0",
    "jasmine-core": "^2.5.2",
    "json-loader": "^0.5.4",
    "karma": "^1.6.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-coverage": "^1.1.1",
    "karma-jasmine": "^1.1.0",
    "karma-mocha-reporter": "^2.2.3",
    "karma-remap-coverage": "^0.1.4",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-webpack": "^2.0.4",
    "ng-router-loader": "^2.1.0",
    "ngc-webpack": "~2.0.0",
    "node-sass": "^4.5.2",
    "npm-run-all": "^4.0.2",
    "optimize-js-plugin": "0.0.4",
    "parse5": "^3.0.2",
    "preload-webpack-plugin": "^1.2.2",
    "protractor": "^5.1.1",
    "raw-loader": "0.5.1",
    "rimraf": "~2.6.1",
    "sass-loader": "^6.0.3",
    "script-ext-html-webpack-plugin": "^1.8.5",
    "source-map-loader": "^0.2.1",
    "string-replace-loader": "~1.2.0",
    "style-loader": "^0.18.1",
    "to-string-loader": "^1.1.5",
    "ts-node": "^3.0.2",
    "tslib": "^1.6.1",
    "tslint": "~4.5.1",
    "tslint-loader": "^3.5.2",
    "typedoc": "^0.7.1",
    "typescript": "^2.3.4",
    "url-loader": "^0.5.8",
    "webpack": "~2.6.1",
    "webpack-dev-middleware": "^1.10.1",
    "webpack-dev-server": "~2.4.2",
    "webpack-dll-bundles-plugin": "^1.0.0-beta.5",
    "webpack-merge": "~4.1.0"
  },

I'm not sure what to check to investigate further

**Comment by Tonio31** [comment]
Updating rxjs from 
 `"rxjs": "~5.0.2",`
to
`"rxjs": "^5.1.0",`

Solve the issue

**Comment by TwanoO67** [comment]
Good to know ! Thank you for the heads up :)
