### ISSUE TITLE
Problem after upgrade to 0.50

### ISSUE THREAD

**Issue by xMase** [TwanoO67/ngx-admin-lte#10]
After clone the last release toggle and sub menu doesn't work anymore

**Comment by TwanoO67** [comment]
Hello,

on which browser ? OS ?

**Comment by xMase** [comment]
Linux chrome - firefox

**Comment by TwanoO67** [comment]
Ok thanks!
It seems to be general, the html syntaxe of admin-lte changed on 2.4.0.
I'm on it, will release a 0.5.1 soon

Thanks for the report

**Comment by TwanoO67** [comment]
I Haven't found any workaround for the menu yet...
Someone has any idea on what change in the html ?

**Comment by TwanoO67** [comment]
Admin lte has been downgraded in the 0.5.1 as a fix for that issue.
