### ISSUE TITLE
Choice of Open Source License

### ISSUE THREAD

**Issue by catull** [TwanoO67/ngx-admin-lte#18]
WTFPL is anarchic and offensive.

It is your right, dear maintainer, to keep it that way, or to switch to a different one.

However, the current license is a deterrent for me.

Since I take Open Source software development seriously, both as a beneficiary as well as a contributor, I certainly cannot identify with nonchalance.

Please consider alternative license models, such as

- APL - [Apache License 2.0](https://opensource.org/licenses/Apache-2.0)
- BSD2 - [BSD 2-Clause "Simplified" or "FreeBSD" license](https://opensource.org/licenses/BSD-2-Clause)
- BSD3 - [BSD 3-Clause "New" or "Revised" license](https://opensource.org/licenses/BSD-3-Clause)
- CDDL - [Common Development and Distribution License](https://opensource.org/licenses/CDDL-1.0)
- EPL - [Eclipse Public License](https://opensource.org/licenses/EPL-1.0)
- GPL - [GNU General Public License](https://opensource.org/licenses/gpl-license)
- ISC - [Internet Systems Consortium](https://www.isc.org/downloads/software-support-policy/isc-license/)
- LGPL - [GNU Library or "Lesser" General Public License](https://opensource.org/licenses/lgpl-license)
- MIT - [MIT license](https://opensource.org/licenses/MIT)
- MPL - [Mozilla Public License 2.0](https://opensource.org/licenses/MPL-2.0)

My favourite ones are: BSD 3-clause, BSD 2-clause, APL, MIT, EPL, MIT or ISC.
I would still stick around with *GPL.

CDDL is out, though.

Choose wisely.

**Comment by xMase** [comment]
I like wmpl license, why is it offensive this license for you?

**Comment by catull** [comment]
Far more important is the "anarchic" part, which deters me.

I cannot associate with anarchic views.
It shows no pride in what you do.

So why one still invest time and brain-power without caring what happens to/with the software ?
What is the motivation ?

As far as the offensive part is concerned, I'd like to show my appreciation for "profanity" with a scene from the "Big Lebowski": [Cuss words"](https://www.youtube.com/watch?v=efZQhYu1E5s&ab_channel=dwheelz24)

I can deal with it in only one context: no-fuss comedy.
That's where I draw the line.

Had I paid more attention to the license, I would not have contributed.
It is too late now, I have made some contributions, which I will not revoke.

My contributions are small in comparison; the project will carry on, no matter what happens to the license.

One more thing: both AdminLTE and Angular are licensed under MIT.
No obligation there.

**Comment by xMase** [comment]
the community is divided on this license and a license should not be a reason for division into the open source world so  I think that the admin repo should change the license to MIT and take all community power

**Comment by TwanoO67** [comment]
I just read the thread suggested by @catull
And I wasn't aware of the "don't blame me"  missing part of this license.

And I'm ok with @xMase this should not be a division reason.

So listening to both of you, I will change licensing to MIT in the next release

**Comment by catull** [comment]
Thanks to both of you.

I am glad this is issue is treated appropriately.

**Comment by gsouf** [comment]
https://opensource.org/licenses/Fair
