### ISSUE TITLE
SubMenu not opening in sidebar

### ISSUE THREAD

**Issue by Tonio31** [TwanoO67/ngx-admin-lte#2]
Hello,

I'm trying to add submenu links and I followed the small tutorial adding links like this:

```
// define here your own links menu structure
private mylinks: any = [
  {
    'title': 'Home',
    'icon': 'dashboard',
    'link': ['/']
  },
  {
    'title': 'Reports',
    'icon': 'link',
    'sublinks': [
      {
        'title': 'Page 2',
        'link': ['/page/2'],
      },
      {
        'title': 'Page 3',
        'link': ['/page/3'],
      }
    ]
  }
];
```
Unfortunately, it is not working, when I click on the menu link, nothing happens:

![image](https://user-images.githubusercontent.com/11167048/28516711-759b8620-7062-11e7-8355-8a5e0b42ec8d.png)

The submenu is not opening, I compared with the example found on adminlte website and I think I narrowed down the problem on the fact that the class 'menu-open' does NOT get added when you click on the menu link.

Digging further, I see the code in admin-lte that is suppose to be doing that:
```
  //Enable sidebar tree view controls
  if (o.enableControlTreeView) {
    $.AdminLTE.tree('.sidebar');
  }
```

So my guess is that this code is never called by ngx-admin-lte or it is probably me not understanding correctly dependencies. The way I've integrated ngx-admin-lte is by adding this:

```
import { NgxAdminLteModule } from 'ngx-admin-lte';
```

And this in the CSS:
```
@import '~bootstrap/dist/css/bootstrap.css';
@import '~font-awesome/css/font-awesome.css';
@import '~admin-lte/dist/css/AdminLTE.css';
@import '~admin-lte/dist/css/skins/skin-blue.css';
```

Maybe I need to include also some javascript file from admin-lte directly ?

**Comment by TwanoO67** [comment]
At the moment the javascript of admin lte need to be called somewhere. 
For example in your angular-cli json file, like that: https://github.com/TwanoO67/bootstraping-ngx-admin-lte/blob/master/.angular-cli.json

But it could be nice to find a proper way to import the css and js of admin lte directly in ngx-admin-lte module. 
But i havent figured out how, at the moment..

**Comment by Tonio31** [comment]
For people that have the same issue, this was indeed because I needed to pull jquery, bootstrap and adminLTE manually.

For jQuery and Bootstrap, I followed this and it worked like a charm: [https://github.com/AngularClass/angular-starter/wiki/How-to-use-Bootstrap-4-and-Sass-(and-jQuery)](https://github.com/AngularClass/angular-starter/wiki/How-to-use-Bootstrap-4-and-Sass-(and-jQuery))

And for adminLte, I added this line in my app.module.ts:
`import 'admin-lte/dist/js/app.js';`

I suspect there is a better "webpack" way to integrate admin-lte but this is working for me like this.

**Comment by Tonio31** [comment]
Maybe it will be good to precise that you need to pull jquery, bootstrap and adminLTE manually in the Readme (as it was not clear for me, maybe some other people will have the same issue)

**Comment by TwanoO67** [comment]
you're absolutly right.
This installation via npm thing, is still new for me and this package.
I have still a lot to do to optimize that, and any suggestion is appreciated :)
