### ISSUE TITLE
ngx-admin-lte in systemjs issue

### ISSUE THREAD

**Issue by kuangqifu** [TwanoO67/ngx-admin-lte#24]
for my project,I want to add all ngx-admin-lte source files to my project,so I can customs some codes.my projecct use systemjs,but there are so many issues when I do that.can you give me a systemjs branch or some sugesstions?

**Comment by TwanoO67** [comment]
Sorry I don't use systemJs anymore, so I don't know :(

What type of custom codes do you need to do ?
maybe we can add those possibilities to the lib.

**Comment by kuangqifu** [comment]
I got it work now.

**Comment by kuangqifu** [comment]
I got it work now.
1. create a folder,add all files in it.
2. update systemjs.config.js,add some missing map,like 'angular2-toaster,@angular/common/http'etc.
3. add index.ts file and do some change.
4. solve systemjs templateurl issue.
5. update index.html.

It seems there is no animations.I clone bootstraping-ngx-admin-lte from [here](https://github.com/TwanoO67/bootstraping-ngx-admin-lte) and run it,the same.

**Comment by kuangqifu** [comment]
I also want to add top navigation component.features like control-sidebar.

**Comment by TwanoO67** [comment]
Hello,

Version 1.0.0 now lets you add component in top header and menu.
