### ISSUE TITLE
RestService custom header

### ISSUE THREAD

**Issue by chinkan** [TwanoO67/ngx-admin-lte#26]
Could I add my custom header before querying data?

**Comment by TwanoO67** [comment]
Can you explain what modification you would need for that?

Something to change the html ?
Or something to add your own icons on the top right corner?

**Comment by chinkan** [comment]
not html, but http header in RestService, which i can add my custom auth header before calling http.
It would be like changing the headers variable to public in rest.service.ts line 9
https://github.com/TwanoO67/ngx-admin-lte/blob/develop/src/services/rest.service.ts#L9

**Comment by TwanoO67** [comment]
Ok :)
Have you tried if it works with that changing ?
If so you can do a pull request and I will merge it :)

**Comment by chinkan** [comment]
Just create a pull request :)

**Comment by TwanoO67** [comment]
Your pull request has been merged in tag 1.0.0
