### ISSUE TITLE
how to launch it ?

### ISSUE THREAD

**Issue by yashjit** [TwanoO67/ngx-admin-lte#28]
I cloned it from git and after npm install..I did ng serve ..which thorough error as it looks, it can't be build on webpack. how i can do ng serve and run it on local host. I checked others like @ngx-admin which gives webpack support, how can i make it to run same like @ngx-admin.

**Comment by TwanoO67** [comment]
This is only a library, not a webpack bootstrapping
If you are looking for a full example, take a look at: 
   https://github.com/TwanoO67/bootstraping-ngx-admin-lte

**Comment by TwanoO67** [comment]
Alternatively, you ccan start a new angular-cli project, and then install this lib over it :)
