### ISSUE TITLE
Problem with avatar in userService

### ISSUE THREAD

**Issue by Tonio31** [TwanoO67/ngx-admin-lte#3]
Hello,

in the documentation, it is written that for the userService, you should call it like this

```
ngOnInit(){
  let user = new User({
    firstname: "WEBER",
    lastname: "Antoine",
    email: "why-not-yop@yopmail.com",
    avatar_url: "assets/img/user2-160x160.jpg"
  });
```

It didn't work for me, I had to change `avatar_url` by `avatarUrl` and it works

**Comment by TwanoO67** [comment]
noted I will update the doc
Thanks for the report :)
