### ISSUE TITLE
[REQUEST] Update to AdminLte 2.4

### ISSUE THREAD

**Issue by btd1337** [TwanoO67/ngx-admin-lte#32]
It's necessary upgrade the package to support adminlte 2.4.

Thx

**Comment by TwanoO67** [comment]
I already tried but it has some breaking change.
If you have a working version feel free to post a Pull Request.

Related to this: https://github.com/almasaeed2010/AdminLTE/issues/1666

**Comment by btd1337** [comment]
I also tried but there is error with the javascript.

For example, in sidebar not work links with sublevels. If you click  in there you is redirect to login page.

**Comment by TwanoO67** [comment]
Duplicate from #25
