### ISSUE TITLE
getName is not a function

### ISSUE THREAD

**Issue by btd1337** [TwanoO67/ngx-admin-lte#33]
I'm trying to pass a user to application, but this error occurs:

![screenshot from 2018-01-20 15 14 22](https://user-images.githubusercontent.com/11943860/35186173-f790c740-fdf6-11e7-814d-ccac27599a96.jpeg)

It occurs also in MessageBox component.

What can it be?

**Comment by TwanoO67** [comment]
Hello,

It's seems that your object is not a User (model).
Maybe you should transform your object to it.

let user = new User(your_object);

**Comment by btd1337** [comment]
In fact I have been using `export class UserDto extends User` but the issue was that I wasn't instantiating the new object.

`this.user = new UserDto(data);`

Done that worked normally! Thank you!
