### ISSUE TITLE
map' does not exist on type 'Observable<Response>'.

### ISSUE THREAD

**Issue by steve-frank** [TwanoO67/ngx-admin-lte#5]
Hi,
I am trying to use this lib on my existing project.  It is yarn -webpack project.  I followed the steps given by you to configure it in my project. When I trying compile the project , using yarn webpack:build. its giving me 2 error 
'map' does not exist on type 'Observable<Response>'."  
'catch' does not exist on type 'Observable<Response>'.

These errors are in rest.service.ts. I checked the imports in this file they are correct. 
I also checked that. rxjs is there in the lib's node_module. 
FYI, This project of mine already have "rxjs" dependency in node_module. 

Can you please tell me if I am doing something wrong. 
Please let me know if you need any more info on this. I really want to see how I can use this lib in my project. 

Thanks

**Comment by TwanoO67** [comment]
Hello,

Maybe you should check what rxjs version you use.

I'm personnaly using this lib through this:
https://github.com/TwanoO67/bootstraping-ngx-admin-lte

and it use an rxjs 5.1

**Comment by TwanoO67** [comment]
You can also try to import the operator separetly like so:
import {Observable} from 'rxjs/Rx';
 import 'rxjs/add/operator/map';

if you find a syntaxe who work for you/everyone, you can do a merge request for that.

**Comment by steve-frank** [comment]
it worked.. in my package.json the rxjs versiob was "rxjs": "5.4.1". and then I did npm install rxjs again on the root of the project. 
It removed lot of things. then I again did "npm install " on root. it again downloaded my dependencies.  and now when I do yarn webpacl:build on my porject erros are no more there. and version in my package.json is changed to    "rxjs": "^5.4.1".
Thanks
