### ISSUE TITLE
Inconsistent naming for src/models/preferencies.ts

### ISSUE THREAD

**Issue by catull** [TwanoO67/ngx-admin-lte#53]
`preferencies` does not exist as a word; it would be `preferences`
Same spelling as the French word just without accents: préférence (sing.) / préférences (plur.).

All other model classes in src/models are singular words.

I suggest preferencies.ts be renamed to preference.ts.
The class inside accordingly needs to be renamed from `Preferencies` to `Preference`.

**Comment by TwanoO67** [comment]
Hello,

Ok it seems logical :)
It will introduce a BC, but v2 is the good moment to do that ;)

**Comment by catull** [comment]
Sure, no problem.
