### ISSUE TITLE
Need a way to prevent generation and displaying of control side-bar

### ISSUE THREAD

**Issue by catull** [TwanoO67/ngx-admin-lte#55]
I'd like to switch off the control side-bar.

**Comment by TwanoO67** [comment]
you can already by removing the widget in the menu, no ?
( As by default it is switch closed)

**Comment by catull** [comment]
The problem is that in certain situations you can accidentally tab into it and it opens up.
I want it to not be rendered at all, to avoid the situation described entirely.

How do you "remove the widget" ?
Why do I have to remove it ?

If I can - at compile time or during initialisation - specify a flag not to include it at all ?
This is very much similar to the configuration which controls the notifications, messages etc.

I have no need for it in my web app.

**Comment by catull** [comment]
This is what happens currently.

When I start the app, I log on.
The page is shown like this: 
![Initial screen](https://user-images.githubusercontent.com/150055/37334659-c80b83b4-26ac-11e8-87f6-404a6a3453af.png)

I hit the tabular key about 10-12 times, the app shows this: 
![After at least 10 tab key hits](https://user-images.githubusercontent.com/150055/37334763-115f426c-26ad-11e8-8091-e71c349de8fb.png).

Now, the only way out is to hit the tab key 3 or 4 more times, and I am back at the initial screen above.

This is something I want to exclude, no user will accept to have to click 4 tab keys to get back where she/he was.

**Comment by catull** [comment]
At any point in time, you can run into this situation.
So far, only I have discovered it, but it is only a matter of time until a real user spots it.

The cleanest way for me is to not have it generated, at all, the control side-bar.

**Comment by catull** [comment]
By the way, you have that problem too in [bootstraping-ngx-admin-lte](https://github.com/TwanoO67/bootstraping-ngx-admin-lte).

Here is how you can reproduce it.

Clone the repo.
cd into that repo
npm install
npm run start
access it via browser
tab 15 times, you get
![screen shot 2018-03-13 at 11 13 50](https://user-images.githubusercontent.com/150055/37335756-a5e05e60-26af-11e8-8f06-465410fdc3d4.png)

Clicking on the home icon or the cog wheels is not doing anything; not int he sense that you can make the control side-bar disappear.

You have to press the tab key about 5 more times to get out of it.

**Comment by catull** [comment]
In the example of bootstraping-ngx-admin-lte, there is luckily another way out.

You can click twice on the blue cog wheel, between the user-box and the logout button.
Then the side-bar disappears.

But then why do you have two cog wheels ?
Only one works, the other one is purely decorational and unfunctional.

I would remove the second cog wheel entirely.
Also, I would look into how to make the home icon work in this situation.

Perhaps I would reconsider the control side-bar in this case.

**Comment by TwanoO67** [comment]
Hello,

Ok I was not aware of the tabular key thing.
