### ISSUE TITLE
Any way to work with source instead of published package?

### ISSUE THREAD

**Issue by igortg** [TwanoO67/ngx-admin-lte#61]
I tried to run a sample application by installing **ngx-admin-lte** through `npm link`, but had no success.

What is the best way to test changes in the source code?

**Comment by fabioformosa** [comment]
Have you linked your project to the 'dist' folder of ngx-admin-lte?

**Comment by igortg** [comment]
Humm... so I must run `npm link` on the `dist` folder instead of root folder? Will try that.
