### ISSUE TITLE
Question on notification service

### ISSUE THREAD

**Issue by MihaiHoriaPopescu** [TwanoO67/ngx-admin-lte#69]
Hello,
i have some problems on updating the notifications, modify one f them, delete one of them. 
From the source code of notification.service i saw there is a property "public updates: Subject<any> = new Subject<any>();" that should be used, but i dont understand how to use it.
Some sugestions?

**Comment by TwanoO67** [comment]
Hello,

On that property you should emit the full array of notification you want to show.

For that you can use the notification service as seen here:
https://github.com/TwanoO67/bootstraping-ngx-admin-lte/blob/master/src/app/app.component.ts

**Comment by MihaiHoriaPopescu** [comment]
@TwanoO67 Sorry but i did not understand how to do it.

Can you make an example of how i can delete one element of the array of notifications?

**Comment by TwanoO67** [comment]
Through the https://github.com/TwanoO67/ngx-admin-lte/blob/develop/src/services/notifications.service.ts

You can access the full notification list, remove the one you don't want anymore, and submit the rest

**Comment by MihaiHoriaPopescu** [comment]
But the notificationList is private.

**Comment by TwanoO67** [comment]
Yes but you can access the "notifications" subject to receive the last version of it

**Comment by MihaiHoriaPopescu** [comment]
Sorry but i dont really know how to use the rxjs lib (Subject, ReplaySubject).
Can you make an example of how to modify/delete elements using the "notifications" property?
Thanks.

**Comment by TwanoO67** [comment]
To modify something you have the stream of updates.

myNotifService.updates.next(function(notification: Notification): INotificationsOperation {
        return (notifications: Notification[]) => {
           //here you can access the full tab of notifications
          // search and modify or delete the one you want
         // then return the full tab 
         return notifications;
        };
      });

**Comment by TwanoO67** [comment]
If you want more big picture advise on rxjs I recommend this tutorial here:

https://gist.github.com/staltz/868e7e9bc2a7b8c1f754

**Comment by MihaiHoriaPopescu** [comment]
Ok, thanks!
