### ISSUE TITLE
Missing document

### ISSUE THREAD

**Issue by wgbn** [TwanoO67/ngx-admin-lte#7]
I'm holding hands, have no reference how to use the layouts, widgets and services!

**Comment by TwanoO67** [comment]
Hello,

You can look the readme, or use the example project: https://github.com/TwanoO67/bootstraping-ngx-admin-lte

**Comment by wgbn** [comment]
Sorry, but I have read this document backwards and it is really extremely superficial. It just says there are some services and it does not tell you how they work

**Comment by TwanoO67** [comment]
There's example of code in the readme. Please be more specific if you want any help...

**Comment by TwanoO67** [comment]
More documentation has been added, please ask if you need any more help on something.
